config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

    def new
    end
    
    def create
        @product = Product.new(product_params)
    
        @product.save
        redirect_to @product
    end
    
    private
    def product_params
        params.require(:product).permit(:name, :stock)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cgstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
 <tr>
   <th>Name</th>
   <th>Stock</th>
 </tr>

 <% @products.each do |product| %>
   <tr>
     <td><%= product.name %></td>
     <td><%= product.stock %></td>
     <td><%= link_to 'Show', product_path(product) %></td>
   </tr>
 <% end %>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= form_with scope: :product, url: products_path, local: true do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
   
    <p>
      <%= form.label :stock %><br>
      <%= form.text_area :stock %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/products/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @product.name %>
</p>

<p>
    <strong>Stock:</strong>
    <%= @product.stock %>
</p>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>